### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by bpinto** [kefirjs/kefir-test-utils#368]
Hi, @mAAdhaTTah could you please release a new version? I would like to update [jest-kefir](https://github.com/kefirjs/jest-kefir) to use this new version.

**Comment by mAAdhaTTah** [comment]
Unfortunately, I won't be able to do this until I return home Sunday at the earliest.

**Comment by mAAdhaTTah** [comment]
[v2.0.0 published](https://github.com/kefirjs/kefir-test-utils/releases/tag/v2.0.0)
