### ISSUE TITLE
Testing fromPromise fails

### ISSUE THREAD

**Issue by fernandogmar** [kefirjs/kefir-test-utils#574]
Hi!

just trying to test a stream that contains a `fromPromise` call, it does not give me the expected results. But if we would replace it with `constant` it works fine. Below an example:

```
const events = {
  a: value(1),
  b: value(2),
  c: end()
};
           withFakeTime((tick) => {
            const obs = stream();
            const out_1 = obs.flatMap( 
                (v) => Kefir.fromPromise(Promise.resolve(v+1))
            );
            const out_2 = obs.map(v => 0);
            const out = Kefir.merge([out_2, out_1]);
            const { log } = watchWithTime(out);
            sendFrames(obs, {
                frames: parseDiagram('abc', events),
                advance: () => tick(200),
            });
            out.onEnd(() => {
                t.deepEqual(log, [
                    [0, value(0)],
                    [0, value(1+1)],
                    [200, value(0)],
                    [200, value(2+1)],
                    [400, end()],
                ]);
            });
        });
```

**Comment by mAAdhaTTah** [comment]
Promises are async always so you're going to get different results compared to `constant` which is sync.

**Comment by fernandogmar** [comment]
Thanks! then I am missing an async version for testing streams with promises 😅 
...anyway, I have already got a different approach using directly sinon. Thanks again!

**Comment by mAAdhaTTah** [comment]
No problem, I don't think the built in test tooling handles _actual_ async particularly well. It sort of pretends to handle async with the `parseDiagram` and underlying clock mocking but if you need to use an actual promise, you'll need to deal with that in the test.
